// frontend/src/redux/constants/videoConstants.js

export const VIDEO_PROGRESS_REQUEST = 'VIDEO_PROGRESS_REQUEST';
export const VIDEO_PROGRESS_SUCCESS = 'VIDEO_PROGRESS_SUCCESS';
export const VIDEO_PROGRESS_FAIL = 'VIDEO_PROGRESS_FAIL';

export const UPDATE_VIDEO_PROGRESS_REQUEST = 'UPDATE_VIDEO_PROGRESS_REQUEST';
export const UPDATE_VIDEO_PROGRESS_SUCCESS = 'UPDATE_VIDEO_PROGRESS_SUCCESS';
export const UPDATE_VIDEO_PROGRESS_FAIL = 'UPDATE_VIDEO_PROGRESS_FAIL';

export const CLEAR_VIDEO_PROGRESS = 'CLEAR_VIDEO_PROGRESS';
